### ISSUE TITLE
Error while fetching v0.0.3

### ISSUE THREAD

**Issue by vishmit123** [inuits/terraform-provider-cortex#10]
Getting error while doing terraform init:

**Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider inuits/cortex:
no available releases match the given constraints 0.0.3**

**Comment by vishmit123** [comment]
I see in tag v0.0.3, the version declared in makeFile is 0.1

**Comment by roidelapluie** [comment]
what does your main.tf look like?

**Comment by vishmit123** [comment]
`terraform {
  required_providers {
    cortex = {
      source = "inuits/cortex"
      version = "0.0.3"
    }
  }
}`





`

**Comment by vishmit123** [comment]
terraform {
  required_providers {
    cortex = {
      source = "inuits/cortex"
      version = "0.0.3"
    }
  }

  required_version = ">= 0.13"
}

**Comment by vishmit123** [comment]
Hi, waiting for tag v0.0.3 to be updated with the latest master commit.

**Comment by roidelapluie** [comment]
Why do you think that v0.0.3 is not working? Can you share some logs?

**Comment by vishmit123** [comment]
Ah !! looks like the terraform env on my system was messed up. It was pointing to local plugins instead of terraform registry. NO ACTION REQUIRED. You can close the issue.
