### ISSUE TITLE
Error: requested resource not found

### ISSUE THREAD

**Issue by vishmit123** [inuits/terraform-provider-cortex#8]
the cortex package https://github.com/grafana/cortex-tools/pkg/client seems to be using  API v1 by default. The cortex deployment in my case uses only legacy API  "/api/prom/rules". Cortex client has a parameter : UseLegacyRoutes <bool> . The same can be included in the provider definition.

**Comment by vishmit123** [comment]
https://github.com/grafana/cortex-tools/blob/master/pkg/client/client.go#L35

**Comment by vishmit123** [comment]
but this may require some other changes as well

**Comment by roidelapluie** [comment]
> but this may require some other changes as well

Can you please explain?

**Comment by vishmit123** [comment]
the format of the request body in the case of legacy routes is different. So it won't work just by changing the routes.
